### ISSUE TITLE
Allow for adding mqtt username/password details within the config.

### ISSUE THREAD

**Issue by somejavadev** [ned-kelly/docker-lechacal-homeassistant#1]
Hi,

Some mqtt servers require authentication. I am opening this ticket to associate it with a pull request.

**Comment by somejavadev** [comment]
Having a look the great work @gtricot is doing at this fork: https://github.com/gtricot/docker-lechacal-homeassistant this functionality is already being built in there.

**Comment by gtricot** [comment]
Hi @somejavadev !

Glad to see my fork is used by someone else ! 
I'm currently working on little enhancements for better reliability and I released version 0.2.0 today.
I just opened Issues and Discussions sections on my forked repo, don't hesitate to ask me for features or contribute directly.

**Comment by somejavadev** [comment]
Hi @gtricot,

I have created a pull request with some modifications I have made locally to mine which I find useful. If you are interested you can adopt them for yourself or merge them as is. I will also see if I can build in a mechanism to delay the mqtt reporting as it currently reports as soon as serial data is received which is almost every second. The idea being that it only reports back at a set interval with the latest data eg. every 5 minutes, this will be configurable via an environment variable.
